# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=example
     - MYSQL_DATABASE=myspend_dev
    ports:
      - 3306:3306
    # db-data to proj folder (tested, for the future...)  
    # volumes:
    #  - ./data/db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080